services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  json-server:
    image: vimagick/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "4000:4000"
    command: -H 0.0.0.0 -p 4000 -w /data/db.json
